apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/fastapi-repo/user-service:v1  # Change for each service
        ports:
        - containerPort: 8000
