name: Deploy FastAPI to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy to GKE
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: fastapi-cluster-1
      GKE_REGION: us-central1
      IMAGE_NAME: fastapi-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/fastapi-repo/${{ env.IMAGE_NAME }}:latest .
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/fastapi-repo/${{ env.IMAGE_NAME }}:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
            --region ${{ env.GKE_REGION }} \
            --project ${{ env.PROJECT_ID }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
